#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

[[layers]]
  name = "lang
[layers]]
  name = "lang#latex"
[[layers]]
  name = "lang#toml"
[[layers]]
  name = "checkers"
[[layers]]
  name = "git"
  git_plugin = 'fugitive'
[[layers]]
  name = "fzf"
[[layers]]
  name = "lang#powershell"
[[layers]]
  name = "lang#python"
  enable_typeinfo = true
  format_on_save = true
  enabled_linters = ['python', 'pylint']
  python_file_head = [
      '#!/usr/bin/env python',
      '# -*- coding: utf-8 -*-',
      '',
      ''
  ]
[[layers]]
    name = 'lang#c'
    format_on_save = true
# Enable autocomplete layer
[[layers]]
  name = "sudo"

[[layers]]
  name = "telescope"
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = "default"

[[layers]]
  name = "tmux"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'core'
enable_netrw = true
[[custom_plugins]]
    name = "scrooloose/nerdtree"
    merged = false


[[custom_plugins]]
    name = "airblade/vim-gitgutter"
    merged = false

[[custom_plugins]]
    name = "tpope/vim-fugitive"
    merged = false

[[custom_plugins]]
    name = "tpope/vim-commentary"
    merged = false

[[custom_plugins]]
    name = "maxbrunsfeld/vim-yankstack"
    merged = false

[[custom_plugins]]
    name = "mileszs/ack.vim"
    merged = false

[[custom_plugins]]
    name = "terryma/vim-multiple-cursors"
    merged = false

[[custom_plugins]]
    name = "vim-scripts/bufexplorer.zip"
    merged = false
[[custom_plugins]]
    name = "rhysd/vim-clang-format"
    merged = false

